//+------------------------------------------------------------------+
//|                                  ParabolicSARTrendReversalEA.mq5 |
//|                                     Generated by Gemini AI Model |
//+------------------------------------------------------------------+
#property copyright "Expert MQL5 Developer"
#property link      ""
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\SymbolInfo.mqh>
#include <Trade\PositionInfo.mqh>

//--- Input Groups ---
input group "=== Parabolic SAR ==="
input double   SARStep = 0.02;                // SAR Step
input double   SARMaximum = 0.20;             // SAR Maximum

input group "=== EMA Filter ==="
input bool     UseEMAFilter = true;           // Use EMA Filter
input int      EMAPeriod = 50;                // EMA Period
input bool     UseEMASlopeFilter = false;     // Use EMA Slope Filter

input group "=== ADX Filter ==="
input bool     UseADXFilter = false;          // Use ADX Filter
input int      ADXPeriod = 14;                // ADX Period
input double   MinimumADX = 20.0;             // Minimum ADX
input bool     UseMaximumADX = false;         // Use Maximum ADX
input double   MaximumADX = 50.0;             // Maximum ADX

input group "=== Candle Confirmation ==="
input bool     UseCandleConfirmation = true;        // Use Candle Confirmation
input bool     UseStrongCandleConfirmation = false; // Use Strong Candle Confirmation
input double   MinimumBodyATR = 0.20;               // Minimum Body Size (ATR Multiplier)

input group "=== Reversal Filter ==="
input bool     UseReversalDistanceFilter = true;    // Use Reversal Distance Filter
input double   MinimumReversalDistanceATR = 0.20;   // Minimum Reversal Distance (ATR Multiplier)

input group "=== ATR Risk Management ==="
input int      ATRPeriod = 14;                // ATR Period
input double   StopLossATRMultiplier = 1.5;   // Stop Loss (ATR Multiplier)
input double   TakeProfitATRMultiplier = 2.5; // Take Profit (ATR Multiplier)

input group "=== Risk/Reward ==="
input bool     UseMinimumRiskReward = true;   // Use Minimum Risk/Reward
input double   MinimumRiskReward = 1.2;       // Minimum Risk/Reward Ratio

input group "=== Position Sizing ==="
input bool     UseRiskBasedLot = false;       // Use Risk-Based Lot
input double   RiskPercent = 1.0;             // Risk Percent (Equity)
input double   FixedLot = 0.01;               // Fixed Lot
input double   MinLot = 0.01;                 // Minimum Lot
input double   MaxLot = 100.0;                // Maximum Lot

input group "=== Exit ==="
input bool     CloseOnOppositeSAR = true;     // Close on Opposite SAR Flip
input bool     UseEMAExit = false;            // Close on EMA Cross
input bool     UseSARStopLossTrailing = false;// SAR Trailing Stop
input bool     UseATRTrailingStop = false;    // ATR Trailing Stop
input double   TrailingStopATRMultiplier = 1.5;// ATR Trailing Stop Multiplier
input bool     UseBreakEven = false;          // Use Break-Even
input double   BreakEvenTriggerATR = 1.0;     // Break-Even Trigger (ATR Multiplier)
input int      BreakEvenOffsetPoints = 10;    // Break-Even Offset (Points)

input group "=== Trading Control ==="
input ulong    MagicNumber = 123456;          // Magic Number
input int      MaxPositions = 1;              // Maximum Positions per Symbol
input bool     AllowBuy = true;               // Allow Buy Trades
input bool     AllowSell = true;              // Allow Sell Trades
input ulong    SlippagePoints = 3;            // Slippage (Points)
input bool     UseSpreadFilter = true;        // Use Spread Filter
input int      MaxSpreadPoints = 30;          // Maximum Spread (Points)
input bool     UseTradingSession = false;     // Use Trading Session
input int      StartHour = 3;                 // Start Hour
input int      StartMinute = 0;               // Start Minute
input int      EndHour = 22;                  // End Hour
input int      EndMinute = 0;                 // End Minute
input bool     UseCooldown = true;            // Use Cooldown After Trade
input int      CooldownBars = 3;              // Cooldown (Bars)

//--- Global Variables ---
CTrade         trade;
CSymbolInfo    symInfo;
CPositionInfo  posInfo;

int            sar_handle = INVALID_HANDLE;
int            ema_handle = INVALID_HANDLE;
int            adx_handle = INVALID_HANDLE;
int            atr_handle = INVALID_HANDLE;

datetime       last_bar_time = 0;

double         sar_buffer[];
double         ema_buffer[];
double         adx_buffer[];
double         atr_buffer[];
MqlRates       rates[];

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetDeviationInPoints(SlippagePoints);
   trade.SetTypeFilling(ORDER_FILLING_FOK);
   symInfo.Name(_Symbol);
   
   ArraySetAsSeries(sar_buffer, true);
   ArraySetAsSeries(ema_buffer, true);
   ArraySetAsSeries(adx_buffer, true);
   ArraySetAsSeries(atr_buffer, true);
   ArraySetAsSeries(rates, true);

   sar_handle = iSAR(_Symbol, _Period, SARStep, SARMaximum);
   ema_handle = iMA(_Symbol, _Period, EMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   adx_handle = iADX(_Symbol, _Period, ADXPeriod);
   atr_handle = iATR(_Symbol, _Period, ATRPeriod);

   if(sar_handle == INVALID_HANDLE || ema_handle == INVALID_HANDLE || 
      adx_handle == INVALID_HANDLE || atr_handle == INVALID_HANDLE)
     {
      Print("Failed to create indicator handles.");
      return(INIT_FAILED);
     }

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   if(sar_handle != INVALID_HANDLE) IndicatorRelease(sar_handle);
   if(ema_handle != INVALID_HANDLE) IndicatorRelease(ema_handle);
   if(adx_handle != INVALID_HANDLE) IndicatorRelease(adx_handle);
   if(atr_handle != INVALID_HANDLE) IndicatorRelease(atr_handle);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!symInfo.RefreshRates()) return;

   // Tick-based management (Break-even and ATR trailing)
   ManagePositionsTick();

   // New Bar detection
   datetime current_time = iTime(_Symbol, _Period, 0);
   if(current_time != last_bar_time)
     {
      if(UpdateBuffers())
        {
         ManagePositionsNewBar(); // Exits and SAR trailing
         
         if(CheckTradingSession() && CheckCooldown() && CheckSpread())
           {
            if(CountOwnPositions() < MaxPositions)
              {
               if(AllowBuy && CheckBuyConditions()) OpenBuy();
               else if(AllowSell && CheckSellConditions()) OpenSell();
              }
           }
         last_bar_time = current_time;
        }
     }
  }

//+------------------------------------------------------------------+
//| Update Indicator Buffers                                         |
//+------------------------------------------------------------------+
bool UpdateBuffers()
  {
   if(CopyBuffer(sar_handle, 0, 0, 3, sar_buffer) < 3) return false;
   if(CopyBuffer(ema_handle, 0, 0, 3, ema_buffer) < 3) return false;
   if(CopyBuffer(adx_handle, 0, 0, 3, adx_buffer) < 3) return false;
   if(CopyBuffer(atr_handle, 0, 0, 3, atr_buffer) < 3) return false;
   if(CopyRates(_Symbol, _Period, 0, 3, rates) < 3) return false;
   
   return true;
  }

//+------------------------------------------------------------------+
//| Check Buy Conditions                                             |
//+------------------------------------------------------------------+
bool CheckBuyConditions()
  {
   // Primary SAR Flip
   if(!(sar_buffer[2] > rates[2].high && sar_buffer[1] < rates[1].low)) return false;

   // Candle Confirmation
   if(UseCandleConfirmation && rates[1].close <= rates[1].open) return false;
   if(UseStrongCandleConfirmation && MathAbs(rates[1].close - rates[1].open) < atr_buffer[1] * MinimumBodyATR) return false;

   // EMA Filter
   if(UseEMAFilter && rates[1].close <= ema_buffer[1]) return false;
   if(UseEMASlopeFilter && ema_buffer[1] <= ema_buffer[2]) return false;

   // ADX Filter
   if(UseADXFilter && adx_buffer[1] < MinimumADX) return false;
   if(UseMaximumADX && adx_buffer[1] > MaximumADX) return false;

   // Reversal Distance Filter
   if(UseReversalDistanceFilter)
     {
      double distance = rates[1].close - sar_buffer[1];
      if(distance < atr_buffer[1] * MinimumReversalDistanceATR) return false;
     }

   return true;
  }

//+------------------------------------------------------------------+
//| Check Sell Conditions                                            |
//+------------------------------------------------------------------+
bool CheckSellConditions()
  {
   // Primary SAR Flip
   if(!(sar_buffer[2] < rates[2].low && sar_buffer[1] > rates[1].high)) return false;

   // Candle Confirmation
   if(UseCandleConfirmation && rates[1].close >= rates[1].open) return false;
   if(UseStrongCandleConfirmation && MathAbs(rates[1].close - rates[1].open) < atr_buffer[1] * MinimumBodyATR) return false;

   // EMA Filter
   if(UseEMAFilter && rates[1].close >= ema_buffer[1]) return false;
   if(UseEMASlopeFilter && ema_buffer[1] >= ema_buffer[2]) return false;

   // ADX Filter
   if(UseADXFilter && adx_buffer[1] < MinimumADX) return false;
   if(UseMaximumADX && adx_buffer[1] > MaximumADX) return false;

   // Reversal Distance Filter
   if(UseReversalDistanceFilter)
     {
      double distance = sar_buffer[1] - rates[1].close;
      if(distance < atr_buffer[1] * MinimumReversalDistanceATR) return false;
     }

   return true;
  }

//+------------------------------------------------------------------+
//| Open Buy                                                         |
//+------------------------------------------------------------------+
void OpenBuy()
  {
   double entry_price = symInfo.Ask();
   double sl = NormalizePrice(entry_price - atr_buffer[1] * StopLossATRMultiplier);
   double tp = NormalizePrice(entry_price + atr_buffer[1] * TakeProfitATRMultiplier);

   if(!ValidateRiskReward(entry_price, sl, tp))
     {
      Print("Buy rejected by Risk/Reward filter");
      return;
     }

   double lot = CalculateLotSize(MathAbs(entry_price - sl));
   if(lot <= 0) return;

   sl = AdjustStopsForBroker(entry_price, sl, true);
   tp = AdjustStopsForBroker(entry_price, tp, true);

   if(trade.Buy(lot, _Symbol, entry_price, sl, tp, "SAR Buy"))
     {
      Print("Successful BUY. Ticket: ", trade.ResultOrder());
     }
   else
     {
      Print("BUY failed. Retcode: ", trade.ResultRetcode(), " Desc: ", trade.ResultRetcodeDescription());
     }
  }

//+------------------------------------------------------------------+
//| Open Sell                                                        |
//+------------------------------------------------------------------+
void OpenSell()
  {
   double entry_price = symInfo.Bid();
   double sl = NormalizePrice(entry_price + atr_buffer[1] * StopLossATRMultiplier);
   double tp = NormalizePrice(entry_price - atr_buffer[1] * TakeProfitATRMultiplier);

   if(!ValidateRiskReward(entry_price, sl, tp))
     {
      Print("Sell rejected by Risk/Reward filter");
      return;
     }

   double lot = CalculateLotSize(MathAbs(sl - entry_price));
   if(lot <= 0) return;

   sl = AdjustStopsForBroker(entry_price, sl, false);
   tp = AdjustStopsForBroker(entry_price, tp, false);

   if(trade.Sell(lot, _Symbol, entry_price, sl, tp, "SAR Sell"))
     {
      Print("Successful SELL. Ticket: ", trade.ResultOrder());
     }
   else
     {
      Print("SELL failed. Retcode: ", trade.ResultRetcode(), " Desc: ", trade.ResultRetcodeDescription());
     }
  }

//+------------------------------------------------------------------+
//| Validate Risk Reward                                             |
//+------------------------------------------------------------------+
bool ValidateRiskReward(double entry, double sl, double tp)
  {
   if(!UseMinimumRiskReward) return true;
   double risk = MathAbs(entry - sl);
   double reward = MathAbs(tp - entry);
   if(risk == 0) return false;
   return (reward / risk) >= MinimumRiskReward;
  }

//+------------------------------------------------------------------+
//| Calculate Lot Size                                               |
//+------------------------------------------------------------------+
double CalculateLotSize(double sl_distance)
  {
   double lot = FixedLot;
   if(UseRiskBasedLot)
     {
      double equity = AccountInfoDouble(ACCOUNT_EQUITY);
      double risk_amount = equity * (RiskPercent / 100.0);
      double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
      double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
      
      if(tick_value > 0 && tick_size > 0 && sl_distance > 0)
        {
         double sl_points = sl_distance / tick_size;
         lot = risk_amount / (sl_points * tick_value);
        }
     }

   double min_vol = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max_vol = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double step_vol = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   lot = MathFloor(lot / step_vol) * step_vol;
   if(lot < min_vol) lot = min_vol;
   if(lot > max_vol) lot = max_vol;
   if(lot < MinLot) lot = MinLot;
   if(lot > MaxLot) lot = MaxLot;

   return lot;
  }

//+------------------------------------------------------------------+
//| Tick-based Position Management                                   |
//+------------------------------------------------------------------+
void ManagePositionsTick()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == MagicNumber)
           {
            double new_sl = posInfo.StopLoss();
            bool modify = false;

            // Break-Even
            if(UseBreakEven)
              {
               if(posInfo.PositionType() == POSITION_TYPE_BUY)
                 {
                  if(symInfo.Bid() >= posInfo.PriceOpen() + atr_buffer[1] * BreakEvenTriggerATR)
                    {
                     double be_price = posInfo.PriceOpen() + BreakEvenOffsetPoints * _Point;
                     if(new_sl < be_price) { new_sl = be_price; modify = true; }
                    }
                 }
               else if(posInfo.PositionType() == POSITION_TYPE_SELL)
                 {
                  if(symInfo.Ask() <= posInfo.PriceOpen() - atr_buffer[1] * BreakEvenTriggerATR)
                    {
                     double be_price = posInfo.PriceOpen() - BreakEvenOffsetPoints * _Point;
                     if(new_sl > be_price || new_sl == 0) { new_sl = be_price; modify = true; }
                    }
                 }
              }

            // ATR Trailing
            if(UseATRTrailingStop)
              {
               if(posInfo.PositionType() == POSITION_TYPE_BUY)
                 {
                  double atr_sl = NormalizePrice(symInfo.Bid() - atr_buffer[1] * TrailingStopATRMultiplier);
                  if(atr_sl > new_sl) { new_sl = atr_sl; modify = true; }
                 }
               else if(posInfo.PositionType() == POSITION_TYPE_SELL)
                 {
                  double atr_sl = NormalizePrice(symInfo.Ask() + atr_buffer[1] * TrailingStopATRMultiplier);
                  if(atr_sl < new_sl || new_sl == 0) { new_sl = atr_sl; modify = true; }
                 }
              }

            if(modify)
              {
               new_sl = NormalizePrice(new_sl);
               if(MathAbs(new_sl - posInfo.StopLoss()) > _Point)
                  trade.PositionModify(posInfo.Ticket(), new_sl, posInfo.TakeProfit());
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| New Bar Position Management                                      |
//+------------------------------------------------------------------+
void ManagePositionsNewBar()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == MagicNumber)
           {
            // Opposite SAR Exit
            if(CloseOnOppositeSAR)
              {
               if(posInfo.PositionType() == POSITION_TYPE_BUY && sar_buffer[2] < rates[2].low && sar_buffer[1] > rates[1].high)
                 {
                  trade.PositionClose(posInfo.Ticket());
                  Print("Closed BUY on Opposite SAR Flip");
                  continue;
                 }
               else if(posInfo.PositionType() == POSITION_TYPE_SELL && sar_buffer[2] > rates[2].high && sar_buffer[1] < rates[1].low)
                 {
                  trade.PositionClose(posInfo.Ticket());
                  Print("Closed SELL on Opposite SAR Flip");
                  continue;
                 }
              }

            // EMA Exit
            if(UseEMAExit)
              {
               if(posInfo.PositionType() == POSITION_TYPE_BUY && rates[1].close < ema_buffer[1])
                 {
                  trade.PositionClose(posInfo.Ticket());
                  Print("Closed BUY on EMA Exit");
                  continue;
                 }
               else if(posInfo.PositionType() == POSITION_TYPE_SELL && rates[1].close > ema_buffer[1])
                 {
                  trade.PositionClose(posInfo.Ticket());
                  Print("Closed SELL on EMA Exit");
                  continue;
                 }
              }

            // SAR Trailing Stop
            if(UseSARStopLossTrailing)
              {
               double new_sl = posInfo.StopLoss();
               bool modify = false;

               if(posInfo.PositionType() == POSITION_TYPE_BUY)
                 {
                  if(sar_buffer[1] < rates[1].low && sar_buffer[1] > new_sl)
                    {
                     new_sl = sar_buffer[1];
                     modify = true;
                    }
                 }
               else if(posInfo.PositionType() == POSITION_TYPE_SELL)
                 {
                  if(sar_buffer[1] > rates[1].high && (sar_buffer[1] < new_sl || new_sl == 0))
                    {
                     new_sl = sar_buffer[1];
                     modify = true;
                    }
                 }

               if(modify)
                 {
                  new_sl = NormalizePrice(new_sl);
                  if(MathAbs(new_sl - posInfo.StopLoss()) > _Point)
                     trade.PositionModify(posInfo.Ticket(), new_sl, posInfo.TakeProfit());
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Count Own Positions                                              |
//+------------------------------------------------------------------+
int CountOwnPositions()
  {
   int count = 0;
   for(int i = 0; i < PositionsTotal(); i++)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == MagicNumber)
            count++;
        }
     }
   return count;
  }

//+------------------------------------------------------------------+
//| Check Cooldown                                                   |
//+------------------------------------------------------------------+
bool CheckCooldown()
  {
   if(!UseCooldown) return true;
   
   HistorySelect(0, TimeCurrent());
   int total = HistoryDealsTotal();
   datetime last_close = 0;

   for(int i = total - 1; i >= 0; i--)
     {
      ulong ticket = HistoryDealGetTicket(i);
      if(HistoryDealGetInteger(ticket, DEAL_MAGIC) == MagicNumber &&
         HistoryDealGetString(ticket, DEAL_SYMBOL) == _Symbol &&
         HistoryDealGetInteger(ticket, DEAL_ENTRY) == DEAL_ENTRY_OUT)
        {
         last_close = (datetime)HistoryDealGetInteger(ticket, DEAL_TIME);
         break;
        }
     }

   if(last_close == 0) return true;
   
   int bars_passed = iBarShift(_Symbol, _Period, last_close);
   return bars_passed >= CooldownBars;
  }

//+------------------------------------------------------------------+
//| Check Trading Session                                            |
//+------------------------------------------------------------------+
bool CheckTradingSession()
  {
   if(!UseTradingSession) return true;
   
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   int current_mins = dt.hour * 60 + dt.min;
   int start_mins = StartHour * 60 + StartMinute;
   int end_mins = EndHour * 60 + EndMinute;

   if(start_mins < end_mins)
     {
      return (current_mins >= start_mins && current_mins <= end_mins);
     }
   else
     {
      return (current_mins >= start_mins || current_mins <= end_mins);
     }
  }

//+------------------------------------------------------------------+
//| Check Spread                                                     |
//+------------------------------------------------------------------+
bool CheckSpread()
  {
   if(!UseSpreadFilter) return true;
   return SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) <= MaxSpreadPoints;
  }

//+------------------------------------------------------------------+
//| Normalize Price                                                  |
//+------------------------------------------------------------------+
double NormalizePrice(double price)
  {
   double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tick_size == 0) return price;
   return NormalizeDouble(MathRound(price / tick_size) * tick_size, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS));
  }

//+------------------------------------------------------------------+
//| Adjust Stops for Broker                                          |
//+------------------------------------------------------------------+
double AdjustStopsForBroker(double entry, double stop_price, bool is_buy)
  {
   if(stop_price == 0) return 0;
   double stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   double freeze_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_FREEZE_LEVEL) * _Point;
   double min_dist = MathMax(stops_level, freeze_level);
   
   if(is_buy)
     {
      if(stop_price < entry) // It's an SL
        {
         if(entry - stop_price < min_dist) stop_price = entry - min_dist;
        }
      else // It's a TP
        {
         if(stop_price - entry < min_dist) stop_price = entry + min_dist;
        }
     }
   else
     {
      if(stop_price > entry) // It's an SL
        {
         if(stop_price - entry < min_dist) stop_price = entry + min_dist;
        }
      else // It's a TP
        {
         if(entry - stop_price < min_dist) stop_price = entry - min_dist;
        }
     }
   return NormalizePrice(stop_price);
  }
//+------------------------------------------------------------------+